apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events {
      worker_connections 1024;
    }

     
    http {

      upstream api {
        server simple-api-service:3000;
      }

      log_format main '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent"';


      server {
        listen 80;
        server_name localhost;
        access_log /var/log/access.log main;

        location / {
          proxy_pass http://api;
        }
      }
    }
---